-- 015_digital_forms.sql
-- Parallel form system: template definitions, per-appointment snapshots,
-- patient-submitted documents, and PDF export records.

-- Admin-configured form template items (global or procedure-specific)
CREATE TABLE form_template_items (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  procedure_type TEXT,                          -- NULL = global default (all procedure types)
  label          TEXT NOT NULL,
  item_type      TEXT NOT NULL CHECK (item_type IN ('patient_upload', 'staff_upload_sign')),
  blank_form_url TEXT,                          -- S3 KEY of blank consent PDF (sign type only)
  required       BOOLEAN NOT NULL DEFAULT false,
  order_index    INTEGER NOT NULL DEFAULT 0,
  is_active      BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Per-appointment snapshot (created at appointment creation time, immutable snapshot)
CREATE TABLE patient_form_items (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id        UUID NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  form_template_item_id UUID REFERENCES form_template_items(id) ON DELETE SET NULL,
  label                 TEXT NOT NULL,
  item_type             TEXT NOT NULL CHECK (item_type IN ('patient_upload', 'staff_upload_sign')),
  staff_file_url        TEXT,                   -- S3 KEY of staff-uploaded consent PDF
  required              BOOLEAN NOT NULL DEFAULT false,
  order_index           INTEGER NOT NULL DEFAULT 0,
  status                TEXT NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'staff_uploaded', 'patient_submitted')),
  staff_id              UUID REFERENCES staff_users(id) ON DELETE SET NULL,
  department_id         UUID REFERENCES departments(id) ON DELETE SET NULL,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Patient-submitted documents and signatures
CREATE TABLE patient_documents (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id       UUID NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  patient_form_item_id UUID NOT NULL REFERENCES patient_form_items(id) ON DELETE CASCADE,
  file_url             TEXT NOT NULL,           -- S3 KEY; presigned on read
  doc_type             TEXT NOT NULL CHECK (doc_type IN ('image_upload', 'signature')),
  uploaded_by_patient  BOOLEAN NOT NULL DEFAULT true,
  is_current           BOOLEAN NOT NULL DEFAULT true,
  submitted_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- PDF export snapshots generated by staff
CREATE TABLE patient_pdf_exports (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id        UUID NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  pdf_key               TEXT NOT NULL,          -- S3 KEY; presigned on read (15min TTL)
  item_count            INTEGER NOT NULL,
  generated_by_staff_id UUID REFERENCES staff_users(id) ON DELETE SET NULL,
  generated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX ON patient_form_items (appointment_id);
CREATE INDEX ON patient_form_items (appointment_id, status);
CREATE INDEX ON patient_documents (patient_form_item_id);
CREATE INDEX ON patient_documents (appointment_id);
CREATE INDEX ON form_template_items (is_active, procedure_type);
CREATE INDEX ON patient_pdf_exports (appointment_id);

-- Only one current document per form item at a time
CREATE UNIQUE INDEX uniq_current_doc_per_item
  ON patient_documents (patient_form_item_id)
  WHERE is_current = true;

-- Prevent duplicate snapshots per template item per appointment
CREATE UNIQUE INDEX uniq_appt_template_item
  ON patient_form_items (appointment_id, form_template_item_id)
  WHERE form_template_item_id IS NOT NULL;

-- Auto-update updated_at on status changes
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER patient_form_items_updated_at
  BEFORE UPDATE ON patient_form_items
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
